version: "3.8"
services:
  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/PaperSurvey
    tty: true
    stdin_open: true
    working_dir: /PaperSurvey
